import type { OutfitPreview } from "@/features/outfits/components/OutfitCard";
import type { WardrobePreviewItem } from "@/features/wardrobe/components/WardrobeItemCard";

export const previewItems: WardrobePreviewItem[] = [
  {
    id: "sample-stone-oxford",
    name: "Stone Oxford Shirt",
    category: "top",
    categoryLabel: "Top",
    color: "#ddd4c2",
    accent: "#766e61",
    meta: "Worn 8 times",
    favorite: true,
  },
  {
    id: "sample-navy-trouser",
    name: "Navy Pleated Trouser",
    category: "bottom",
    categoryLabel: "Bottom",
    color: "#293647",
    accent: "#18202a",
    meta: "Worn 11 times",
  },
  {
    id: "sample-camel-jacket",
    name: "Camel Chore Jacket",
    category: "layer",
    categoryLabel: "Outer layer",
    color: "#9c7250",
    accent: "#5b412e",
    meta: "Worn 4 times",
  },
  {
    id: "sample-black-loafer",
    name: "Black Leather Loafer",
    category: "shoes",
    categoryLabel: "Shoes",
    color: "#292724",
    accent: "#151412",
    meta: "Worn 16 times",
    favorite: true,
  },
  {
    id: "sample-forest-knit",
    name: "Forest Merino Knit",
    category: "top",
    categoryLabel: "Top",
    color: "#455746",
    accent: "#253228",
    meta: "Worn 6 times",
  },
  {
    id: "sample-ecru-jean",
    name: "Ecru Straight Jean",
    category: "bottom",
    categoryLabel: "Bottom",
    color: "#d8d0bf",
    accent: "#958b78",
    meta: "In laundry",
    status: "laundry",
  },
  {
    id: "sample-rust-scarf",
    name: "Rust Wool Scarf",
    category: "accessory",
    categoryLabel: "Accessory",
    color: "#8c493d",
    accent: "#5c2c27",
    meta: "Worn 3 times",
  },
  {
    id: "sample-sand-sneaker",
    name: "Sand Canvas Sneaker",
    category: "shoes",
    categoryLabel: "Shoes",
    color: "#c9bca3",
    accent: "#746b5d",
    meta: "Worn 12 times",
  },
];

export const previewOutfits: OutfitPreview[] = [
  {
    id: "workday-ease",
    name: "Workday Ease",
    occasion: "Office · light rain",
    detail: "A soft neutral base, grounded with navy and a rain-safe shoe.",
    pieces: [
      { category: "top", color: "#ddd4c2", accent: "#766e61" },
      { category: "bottom", color: "#293647" },
      { category: "layer", color: "#9c7250" },
      { category: "shoes", color: "#292724" },
    ],
    favorite: true,
  },
  {
    id: "tonal-weekend",
    name: "Tonal Weekend",
    occasion: "Casual · outdoors",
    detail: "Forest green and ecru keep the look relaxed without feeling unfinished.",
    pieces: [
      { category: "top", color: "#455746" },
      { category: "bottom", color: "#d8d0bf" },
      { category: "shoes", color: "#c9bca3" },
    ],
  },
  {
    id: "quiet-dinner",
    name: "Quiet Dinner",
    occasion: "Dinner · smart casual",
    detail: "A clean dark foundation with one warm accessory for restrained contrast.",
    pieces: [
      { category: "top", color: "#ddd4c2" },
      { category: "bottom", color: "#293647" },
      { category: "accessory", color: "#8c493d" },
      { category: "shoes", color: "#292724" },
    ],
  },
];
